### PR TITLE
Dynamic fav icon

### LINKED ISSUE #59: Favicon should update to publication logo when user is in publication view
The tabula logo should only be the favicon if the user is not in a publication view (IE: viewing posts, permissions, settings or an article)

### PR DESCRIPTION
**Pull request by juliopavila**
closes #59 

# Description

We put the logo as the fav icon if the user has a publication logo. If not, we maintain the default tabula fav icon.

# Additional Context

Also, this PR contains a slight improvement related to the `IPFS Client` inside of the `useFiles.ts` hook because we use Infura (like an IPFS node to create the hash) API, but we missed adding the `projectId` and `apiKey`

### CODE REVIEW

**Review by asgeir-s — CHANGES_REQUESTED** [review]
Since we already use Helmet in this project for manipulating meta tags dynamically, we should probably also use that for changing the favicon dynamically.

**Comment by juliopavila** [comment]
> Since we already use Helmet in this project for manipulating meta tags dynamically, we should probably also use that for changing the favicon dynamically.

I tried a couple of possible walkarounds to set the fav icon dynamically using `React Helmet` but I didn't have luck  https://github.com/nfl/react-helmet/issues/430 for that reason I created a Custom Hook to handle this.

**Comment by manboy-eth** [comment]
> > Since we already use Helmet in this project for manipulating meta tags dynamically, we should probably also use that for changing the favicon dynamically.
> 
> I tried a couple of possible walkarounds to set the fav icon dynamically using `React Helmet` but I didn't have luck [nfl/react-helmet#430](https://github.com/nfl/react-helmet/issues/430) for that reason I created a Custom Hook to handle this.

Aha, okay.

Have you also tried this solution: https://github.com/nfl/react-helmet/issues/430#issuecomment-520364492?

**Comment by juliopavila** [comment]
> > > Since we already use Helmet in this project for manipulating meta tags dynamically, we should probably also use that for changing the favicon dynamically.
> > 
> > 
> > I tried a couple of possible walkarounds to set the fav icon dynamically using `React Helmet` but I didn't have luck [nfl/react-helmet#430](https://github.com/nfl/react-helmet/issues/430) for that reason I created a Custom Hook to handle this.
> 
> Aha, okay.
> 
> Have you also tried this solution: [nfl/react-helmet#430 (comment)](https://github.com/nfl/react-helmet/issues/430#issuecomment-520364492)?

Yes, I tried and no luck

**Review by asgeir-s — APPROVED** [review]

**Pull request merged**
