### PR TITLE
Make it possible for a user to view a list of articles posted

### LINKED ISSUE #13: Make it possible for a user to view a list of articles posted in a publication
Make it possible for a user to browse a publication.

Should include the publication info and the articles posted to the publication.

- [x] App
- [x] Design

It should be possible to get directly to a publication via a URL. Something like: `/publication/{publicationId}`. This should not require or "push" a reader to connect a wallet. Should be browsable for "web2 users".

### PR DESCRIPTION
**Pull request by juliopavila**
closed #13 

Test url: `/#/publication/post/P-0x50c7493bbaa5380152e37f0c7f7295399f41d5eae4657083a9abf2f0b4503407-26`

UI:
image
image

### CODE REVIEW

**Review by asgeir-eth — CHANGES_REQUESTED** [review]
Thank you!

Some feedback:
- [x] We need to have some way of letting users connect their wallet if they load the publication directly (as will probably most often be the case when were make it possible to set up a CNAME for a specific publication). However, I don´t think it should be as prominent as the connect wallet button on the Tablua landing page. Perhaps just a connect wallet link (not a button). What do you think @cedricwaxwing?
- [x] The URL looks strange to me can we make it `/#/publication/{publicationId}` (remove the `post` part?

**Comment by cedricwaxwing** [comment]
> We need to have some way of letting users connect their wallet if they load the publication directly

Julio and I talked about this, and for now, we actually decided that the "connect wallet" button is not really necessary here based on the existing features. The only reason one would currently connect a wallet is to create or join a publication. And since that's the case, it is a bit strange to direct someone to do that from an article page.

Though, now that I'm thinking about it again, there is the chance that it's someone who belongs to the publication, and needs to connect in order to edit something in the article, in which case, I guess it does actually make some sense.

@juliopavila can we add a small, gray, outlined button? Something like this:
https://www.figma.com/file/IaimIfw2pXyR9PlQqdo6M2/Tabula?node-id=456%3A2033

**Comment by asgeir-eth** [comment]
> Julio and I talked about this, and for now, we actually decided that the "connect wallet" button is not really necessary here based on the existing features. The only reason one would currently connect a wallet is to create or join a publication. And since that's the case, it is a bit strange to direct someone to do that from an article page.

I agree we probably do not need it on the article page itself. I was thinking of the publication page, the list of articles.

Since, as I see it people will set up their own domains pointing to their publication page (the list of articles). Like `www.myblog.com`. In that case, I think it's strange that the "owner" needs to go to `tabula.gg` to be able to add or edit things.

Iven without there custom domain, there is no link from the publication (and there should not be) to `tabula.gg`, therefore the user will have to type `tabula.gg` in the address bar in order to get to the "sign-in screen".

**Review by asgeir-eth — CHANGES_REQUESTED** [review]
Code and functionality look good :) 
However, the connect button does not adhere to the Figma design. On the publication page (list of articles) and the article view it should look like this:
image

Now it looks like this:
image

**Comment by juliopavila** [comment]
> Code and functionality look good :) However, the connect button does not adhere to the Figma design. On the publication page (list of articles) and the article view it should look like this: image
> 
> Now it looks like this: image

image

**Review by asgeir-eth — APPROVED** [review]

**Pull request merged**
